### ISSUE TITLE
Unable to connect to APs that aren't broadcasting SSID

### ISSUE THREAD

**Issue by Andronian42** [RattletraPM/gbaxxdumper#1]
Wireless connection previously tested with WarioWare D.I.Y. and Animal Crossing: Wild World. When SSID broadcasting is turned on, it works perfectly; when turned off, stuck on "Connecting to Wi-Fi AP". Network isn't secured with WPA.

**Comment by Andronian42** [comment]
Apologies for that, accidentally hit "enter" on my keyboard while writing this issue out.

**Comment by RattletraPM** [comment]
No worries!

And that's weird, the homebrew does little to no Wi-Fi init on its own - it literally just uses a single function (Wifi_InitDefault) and everything else is taken care of by libndswifi, so that makes me think it could be an issue related to the latter. If that's the case, there wouldn't be much I can do.

You said you tested some commercial games, but could you also try and see if you're able to connect to a network that's not broadcasting its SSID with WiFi enabled homebrew?

**Comment by Andronian42** [comment]
> 
> 
> No worries!
> 
> And that's weird, the homebrew does little to no Wi-Fi init on its own - it literally just uses a single function (Wifi_InitDefault) and everything else is taken care of by libndswifi, so that makes me think it could be an issue related to the latter. If that's the case, there wouldn't be much I can do.
> 
> You said you tested some commercial games, but could you also try and see if you're able to connect to a network that's not broadcasting its SSID with WiFi enabled homebrew?

Ah, I don't know why I didn't test that with homebrew. That's my bad. Once I can get around to it, I'll test that; for now, I'll close this issue.
